/**
 * contextualize-stories.sh — CPA now receives the project manifest
 * (dependency-check.json) and the story's verificationCriteria/storyKind,
 * not just acceptanceCriteria.
 *
 * Root cause, AMSD-2041, 2026-07-31: the Jira ticket had zero acceptance
 * criteria. CPA had nothing else to size complexity from (the story's real
 * verificationCriteria, generated by the spec pass, were captured in
 * story_json but never actually reached cpa-inference.js's buildPrompt()
 * whitelist — see cpa-inference.test.ts), so it defaulted the story to
 * effort:"low" and the implementer got a budget far too small for the real
 * multi-layer feature the VCs described. The manifest gives CPA a second,
 * independent source of grounding (declared deps/stack facts) for exactly
 * this "empty ACs" case.
 *
 * Extracts the REAL, unmodified script blocks (manifest loading +
 * inference_input jq assembly) verbatim and executes them for real via bash
 * — not a re-implementation — so this can never silently diverge from the
 * actual script.
 */
import { describe, it, expect, afterAll } from 'vitest';
import { execFileSync } from 'node:child_process';
import { readFileSync, mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const REPO_ROOT = join(__dirname, '../../../');
const SCRIPT_PATH = join(REPO_ROOT, 'orchestrations/scripts/contextualize-stories.sh');
const src = readFileSync(SCRIPT_PATH, 'utf8');

function extractBlock(startMarker: string, endMarker: string): string {
  const start = src.indexOf(startMarker);
  const end = src.indexOf(endMarker, start);
  if (start === -1 || end === -1) {
    throw new Error(`block not found (start=${start}, end=${end}) — has the script moved/changed shape?`);
  }
  return src.slice(start, end);
}

const manifestBlock = extractBlock(
  '# Project manifest (dependency-check.json)',
  '\n\n# Node 20'
);

const inferenceInputBlock = extractBlock(
  'inference_input=$(jq -n \\',
  "'{story: $story"
) + "'{story: $story, kbChunks: $kbChunks, codebaseSignals: $codebaseSignals,\n" +
    "      formulaEstimate: $formulaEstimate, adjacentStories: $adjacentStories,\n" +
    "      manifest: $manifest, systemPrompt: $systemPrompt}')";

const dir = mkdtempSync(join(tmpdir(), 'ctx-manifest-'));
afterAll(() => rmSync(dir, { recursive: true, force: true }));

function runAssembly(opts: { manifestFileContent?: string; projectConfigDir?: string }): any {
  const scriptPath = join(dir, `run-${Math.random().toString(36).slice(2)}.sh`);
  const env: NodeJS.ProcessEnv = { ...process.env };

  if (opts.manifestFileContent !== undefined) {
    const cfgDir = join(dir, 'cfg');
    require('node:fs').mkdirSync(cfgDir, { recursive: true });
    writeFileSync(join(cfgDir, 'dependency-check.json'), opts.manifestFileContent);
    env.EPAM_PROJECT_CONFIG_DIR = cfgDir;
  } else {
    delete env.EPAM_PROJECT_CONFIG_DIR;
  }

  const script = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    manifestBlock,
    '',
    'story_json=\'{"id":"AMSD-2041","title":"x","acceptanceCriteria":[],"verificationCriteria":["a tester observes the change"]}\'',
    'kb_chunks=\'[]\'',
    'codebase_signals=\'{}\'',
    'formula_est_json=\'{"aiMinutes":10,"cost":0.01,"tokens":100,"turns":1}\'',
    'adjacent_json=\'[]\'',
    'SYSTEM_PROMPT=\'p\'',
    '',
    inferenceInputBlock,
    '',
    'echo "$inference_input"',
  ].join('\n');
  writeFileSync(scriptPath, script);

  const out = execFileSync('bash', [scriptPath], { encoding: 'utf8', env });
  return JSON.parse(out.trim());
}

describe('contextualize-stories.sh — manifest is loaded and passed to CPA (real extracted script blocks)', () => {
  it('loads a real dependency-check.json and includes it verbatim in the inference payload as `manifest`', () => {
    const manifestContent = JSON.stringify({
      requiredDevDependencies: ['@contentstack/live-preview-utils'],
      manifestFile: 'package.json',
    });
    const payload = runAssembly({ manifestFileContent: manifestContent });
    expect(payload.manifest).toEqual(JSON.parse(manifestContent));
  });

  it('passes manifest: null (not an error) when no manifest file exists for the project', () => {
    const payload = runAssembly({});
    expect(payload.manifest).toBeNull();
  });

  it('always includes the full story record, so verificationCriteria reaches the payload alongside the manifest', () => {
    const payload = runAssembly({});
    expect(payload.story.verificationCriteria).toEqual(['a tester observes the change']);
  });
});
