/**
 * Teardown and canonical restore invariants.
 *
 * These tests enforce the fundamental design rule that was violated for weeks:
 *   1. Every run starts with a FULL rm -rf of the output directory — not git clean, not status reset
 *   2. prd.json is restored from travel-app-prd.canonical.json — never from git HEAD
 *   3. profiles.json is restored from profiles.json.original — never from git HEAD
 *   4. The canonical files themselves are NEVER deleted or mutated
 *   5. Pre-flight aborts (exit 1) if the PRD has accumulated split children
 *
 * If any of these tests fail, the run WILL accumulate state from prior runs.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const REPO = join(__dirname, '../../../');
const TIER3 = join(REPO, 'orchestrations/scripts/tier3-travel-app-run.sh');
const PRD_CANONICAL = join(REPO, 'orchestrations/travel-app-prd.canonical.json');
const PRD_RUNTIME = join(REPO, 'orchestrations/travel-app-prd.json');
const PROFILES_ORIG = join(REPO, 'orchestrations/agents/profiles.json.original');

const tier3Src = readFileSync(TIER3, 'utf8');

// ── 1. Full teardown (rm -rf) ────────────────────────────────────────────────
describe('teardown — output directory must be fully deleted before every run', () => {
  it('tier3 uses rm -rf on OUTPUT_DIR before recreating it', () => {
    expect(tier3Src).toMatch(/rm -rf.*OUTPUT_DIR|rm -rf.*\$\{?OUTPUT_DIR/);
  });

  it('tier3 does NOT use git clean as the teardown mechanism', () => {
    // git clean -fdx leaves the .git dir and stale config — insufficient
    const gitCleanIdx = tier3Src.indexOf('git clean -fdx');
    const rmRfIdx = tier3Src.search(/rm -rf.*OUTPUT_DIR|rm -rf.*\$\{?OUTPUT_DIR/);
    if (gitCleanIdx !== -1 && rmRfIdx !== -1) {
      // Both exist — rm -rf must come BEFORE git clean (teardown before any git ops)
      expect(rmRfIdx).toBeLessThan(gitCleanIdx);
    } else if (gitCleanIdx !== -1) {
      // git clean exists but rm -rf does not — this is the broken state
      expect.fail('tier3 uses git clean -fdx without rm -rf — stale artifacts will poison the next run');
    }
    // rm -rf without git clean is fine
  });

  it('tier3 reinitialises a fresh git repo after teardown', () => {
    // After rm -rf, git init + empty commit must follow
    const rmIdx = tier3Src.search(/rm -rf.*OUTPUT_DIR|rm -rf.*\$\{?OUTPUT_DIR/);
    expect(rmIdx).toBeGreaterThan(-1);
    const postTeardown = tier3Src.slice(rmIdx, rmIdx + 400);
    expect(postTeardown).toMatch(/git.*init/);
  });
});

// ── 2. Canonical PRD restore (never git HEAD) ────────────────────────────────
describe('canonical PRD restore — prd.json must come from .canonical.json not git HEAD', () => {
  it('travel-app-prd.canonical.json exists', () => {
    expect(existsSync(PRD_CANONICAL)).toBe(true);
  });

  it('canonical PRD has exactly 4 original user stories — no generated elaborations', () => {
    // The canonical PRD contains ONLY the 4 original user requirements.
    // SKY-005 (dashboard) and SKY-006 (code review) are generated dynamically by the orch.
    // All implementation splits (SKY-001-A, SKY-002a-1, etc.) are generated by spec pass
    // each run and are ephemeral — never stored in the canonical file.
    const canonical = JSON.parse(readFileSync(PRD_CANONICAL, 'utf8'));
    expect(canonical.stories).toHaveLength(4);
  });

  it('canonical PRD stories have no specification.createdFrom (pure user stories, not generated splits)', () => {
    // No hard-coded IDs — structural check only: user stories have no split lineage
    const canonical = JSON.parse(readFileSync(PRD_CANONICAL, 'utf8'));
    const withParent = canonical.stories.filter((s: any) => s?.specification?.createdFrom);
    expect(withParent.map((s: any) => s.id)).toHaveLength(0);
  });

  it('canonical PRD implementationOrder has scaffold and core phases', () => {
    const canonical = JSON.parse(readFileSync(PRD_CANONICAL, 'utf8'));
    const phases = Object.keys(canonical.implementationOrder).sort();
    expect(phases).toContain('scaffold');
    expect(phases).toContain('core');
  });

  it('canonical PRD has no specification.splitOrigin fields (pure user stories, no generated splits)', () => {
    const canonical = JSON.parse(readFileSync(PRD_CANONICAL, 'utf8'));
    const withOrigin = canonical.stories.filter((s: any) => s?.specification?.splitOrigin);
    expect(withOrigin.map((s: any) => s.id)).toHaveLength(0);
  });

  it('canonical PRD has all stories in pending state', () => {
    const canonical = JSON.parse(readFileSync(PRD_CANONICAL, 'utf8'));
    const dirty = canonical.stories.filter((s: any) =>
      s.deprecated !== true && s.status !== 'pending'
    );
    expect(dirty.map((s: any) => `${s.id}:${s.status}`)).toHaveLength(0);
  });

  it('tier3 copies from canonical file, not from git checkout HEAD', () => {
    // The restore must use cp from .canonical.json — NOT git checkout HEAD
    expect(tier3Src).toContain('travel-app-prd.canonical.json');
    expect(tier3Src).not.toMatch(/git checkout HEAD.*prd\.json|git checkout.*HEAD.*travel-app-prd/);
  });

  it('tier3 aborts if canonical file does not exist', () => {
    // Must fail with a clear error message if canonical file is missing
    expect(tier3Src).toMatch(/canonical.*not found|fail.*canonical|canonical.*Aborting/i);
  });
});

// ── 3. Canonical profiles restore ────────────────────────────────────────────
describe('canonical profiles restore — profiles.json must come from profiles.json.original', () => {
  it('profiles.json.original exists', () => {
    expect(existsSync(PROFILES_ORIG)).toBe(true);
  });

  it('tier3 copies profiles.json from profiles.json.original', () => {
    expect(tier3Src).toMatch(/cp.*profiles\.json\.original|PROFILES_ORIG.*profiles\.json/);
  });
});

// ── 4. Originals are never deleted by any script ─────────────────────────────
describe('canonical originals — must never be deleted or overwritten by scripts', () => {
  it('tier3 does not rm or mv the canonical PRD file', () => {
    expect(tier3Src).not.toMatch(/rm.*travel-app-prd\.canonical|mv.*travel-app-prd\.canonical/);
  });

  it('tier3 does not rm or mv profiles.json.original', () => {
    expect(tier3Src).not.toMatch(/rm.*profiles\.json\.original|mv.*profiles\.json\.original/);
  });

  it('orch script does not delete the canonical PRD', () => {
    const orchSrc = readFileSync(
      join(REPO, 'orchestrations/scripts/run-agent-orchestration.sh'), 'utf8'
    );
    expect(orchSrc).not.toMatch(/rm.*travel-app-prd\.canonical/);
  });
});

// ── 5. Drift detection — elaborated PRD must be stable across runs ────────────
describe('drift detection — spec pass elaboration must be re-playable (100% stable)', () => {
  // The spec pass generates implementation stories from the 4 canonical user stories.
  // Re-playability means: the SAME stories, phases, and critical ACs appear every run.
  // These tests guard the invariants that must never drift between runs.

  const prd = existsSync(PRD_RUNTIME) ? JSON.parse(readFileSync(PRD_RUNTIME, 'utf8')) : null;

  it('runtime PRD has no mid-execution split children after restore', () => {
    if (!prd) return;
    const midExec = prd.stories.filter((s: any) =>
      s?.specification?.splitOrigin === 'mid-execution'
    );
    expect(midExec.map((s: any) => s.id)).toHaveLength(0);
  });

  it('spec-pass splits are tagged splitOrigin: spec-pass', () => {
    // Any split story generated after the splitOrigin feature was introduced must be tagged.
    // Legacy splits (from before the feature) have no splitOrigin — skip if all splits are legacy.
    if (!prd) return;
    const allIds = new Set(prd.stories.map((s: any) => s.id));
    const splits = prd.stories.filter((s: any) => {
      const createdFrom = s?.specification?.createdFrom;
      return createdFrom && allIds.has(createdFrom);
    });
    if (splits.length === 0) return; // canonical (pre-spec-pass) PRD — nothing to check
    const anyTagged = splits.some((s: any) => s?.specification?.splitOrigin);
    if (!anyTagged) return; // all are legacy pre-feature splits — skip
    // Mixed or fully-tagged: any split without a tag is a bug
    const untagged = splits.filter((s: any) => !s?.specification?.splitOrigin);
    expect(untagged.map((s: any) => s.id)).toHaveLength(0);
  });

  it('spec-mode-runner marks spec-pass splits with splitOrigin: spec-pass', () => {
    const specRunner = readFileSync(
      join(REPO, 'orchestrations/scripts/spec-mode-runner.js'), 'utf8'
    );
    expect(specRunner).toContain("splitOrigin: 'spec-pass'");
  });

  it('spec-mode-runner marks mid-execution splits with splitOrigin mid-execution', () => {
    const specRunner = readFileSync(
      join(REPO, 'orchestrations/scripts/spec-mode-runner.js'), 'utf8'
    );
    expect(specRunner).toMatch(/splitOrigin\s*=\s*['"]mid-execution['"]/);
  });

  it('tier3 pre-flight aborts on mid-execution splits in the PRD', () => {
    expect(tier3Src).toContain('mid-execution');
    expect(tier3Src).toMatch(/sys\.exit\(1\)|fail.*integrity|ABORT.*mid.exec/i);
  });
});

// ── 6. Worktree sibling directory cleanup ────────────────────────────────────
describe('teardown — parallel worktree dirs must be removed before every run', () => {
  // Run 94 failure: teardown wiped OUTPUT_DIR but left sibling dirs:
  //   skyscanner-app-wt-primary/   and   skyscanner-app-wt-independent/
  // These are NOT inside OUTPUT_DIR so rm -rf OUTPUT_DIR leaves them.
  // Next run's worktree creation sees them as "already exists", skips init,
  // and the merge step fails because the wt-primary / wt-independent branches
  // were never committed into them.

  it('tier3 removes OUTPUT_DIR-wt-* sibling dirs during teardown', () => {
    // Pattern used: for _wt_dir in "${OUTPUT_DIR}-wt-"*; do rm -rf "$_wt_dir"
    expect(tier3Src).toMatch(/OUTPUT_DIR.*-wt-.*rm -rf|rm -rf.*_wt_dir/);
  });

  it('teardown glob covers all wt-* variants with a wildcard (not hardcoded names)', () => {
    // Must use a glob like "${OUTPUT_DIR}-wt-"* — hardcoding wt-primary/wt-independent
    // would break when new worktree types are added.
    expect(tier3Src).toMatch(/OUTPUT_DIR.*-wt-["']\*/);
  });

  it('worktree cleanup happens before mkdir OUTPUT_DIR (teardown order is correct)', () => {
    const rmWtIdx = tier3Src.search(/\$\{?OUTPUT_DIR\}?-wt-/);
    const mkdirIdx = tier3Src.search(/mkdir -p.*OUTPUT_DIR|mkdir -p.*\$\{?OUTPUT_DIR/);
    expect(rmWtIdx).toBeGreaterThan(-1);
    expect(mkdirIdx).toBeGreaterThan(-1);
    expect(rmWtIdx).toBeLessThan(mkdirIdx);
  });

  it('no skyscanner-app-wt-* dirs exist right now (confirms clean state)', () => {
    // If this fails, leftover worktree dirs from a prior run are present.
    // Run: rm -rf /home/bradleyjerome/projects/skyscanner-app-wt-*
    const { execSync } = require('node:child_process');
    const result = execSync(
      'ls /home/bradleyjerome/projects/skyscanner-app-wt-* 2>/dev/null | wc -l',
      { encoding: 'utf8' }
    ).trim();
    expect(
      parseInt(result),
      'Leftover skyscanner-app-wt-* dirs exist — tier3 teardown did not clean them'
    ).toBe(0);
  });
});

// ── 7. Pre-flight aborts on accumulated splits ───────────────────────────────
describe('pre-flight integrity — abort if PRD has mid-execution split children', () => {
  it('tier3 has a PRD integrity guard that exits non-zero on mid-execution splits', () => {
    expect(tier3Src).toContain('mid-execution');
    expect(tier3Src).toMatch(/sys\.exit\(1\)|ABORT.*mid|fail.*Aborting/i);
  });

  it('runtime PRD has no mid-execution splits after restore from canonical', () => {
    if (!existsSync(PRD_RUNTIME)) return;
    const prd = JSON.parse(readFileSync(PRD_RUNTIME, 'utf8'));
    const midExec = prd.stories.filter((s: any) =>
      s?.specification?.splitOrigin === 'mid-execution'
    );
    expect(midExec.map((s: any) => s.id)).toHaveLength(0);
  });
});
