/**
 * A PROJECT FOLDER THAT NOBODY DECLARED IS A FOLDER NOBODY CAN AUDIT.
 *
 * Every consumer resolves project files by HARDCODED FILENAME today —
 * dependency-scan-plugin.js joins the literal 'dependency-check.json',
 * git-ops.sh joins the literal 'plugins.json'. So the layout is hardcoded into every
 * consumer, and nothing anywhere states which files the operator owns, which the
 * pipeline regenerates, which are disposable, or — the one that matters most — which
 * are permitted to be written into a CLIENT repository.
 *
 * manifest.json is that declaration. It is a DECLARATION OF INTENT, never generated by
 * scanning the folder: a generated copy can only agree with reality, so it could not
 * catch an orphan, a stale backup, or a file that failed to deploy. Its whole value is
 * that it was written independently and is compared against what is on disk.
 *
 * These tests are the comparison.
 */
import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(__dirname, '../../../');
const PROJECTS = join(ROOT, 'orchestrations/projects');

/** The manifest declares the folder around it; it does not declare itself. */
const SELF = 'manifest.json';

type Entry = {
  path?: string;
  pattern?: string;
  type?: string;
  role?: string;
  required?: boolean;
  deployTo?: string;
};

function projectsWithManifest(): { name: string; dir: string; manifest: any }[] {
  if (!existsSync(PROJECTS)) return [];
  return readdirSync(PROJECTS)
    .map((name) => ({ name, dir: join(PROJECTS, name) }))
    .filter((p) => {
      try { return statSync(p.dir).isDirectory() && existsSync(join(p.dir, SELF)); } catch { return false; }
    })
    .map((p) => ({ ...p, manifest: JSON.parse(readFileSync(join(p.dir, SELF), 'utf8')) }));
}

/** `prd.json.pre-*` -> anchored regex. Patterns are the only wildcard the manifest allows. */
function patternToRegExp(glob: string): RegExp {
  const escaped = glob.replace(/[.+^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*');
  return new RegExp(`^${escaped}$`);
}

const found = projectsWithManifest();

describe('there is something to check — otherwise every assertion below is vacuous', () => {
  it('at least one project declares a manifest', () => {
    expect(found.length, `no project under ${PROJECTS} has a ${SELF}`).toBeGreaterThan(0);
  });

  it('each manifest declares a non-trivial file set', () => {
    for (const p of found) {
      expect(Object.keys(p.manifest.files || {}).length, `${p.name} declares no files`).toBeGreaterThan(3);
    }
  });
});

describe.each(found)('$name', ({ dir, manifest }) => {
  const entries: Entry[] = Object.values(manifest.files || {});

  it('every REQUIRED declared file exists on disk', () => {
    const missing = entries
      .filter((e) => e.required && e.path)
      .map((e) => e.path as string)
      .filter((rel) => !existsSync(join(dir, rel)));
    expect(missing, 'declared as required but absent — the declaration is a lie').toEqual([]);
  });

  it('every file on disk is DECLARED — no orphans', () => {
    // The assertion that catches stale backups and files someone dropped in by hand.
    const exact = new Set(entries.map((e) => e.path).filter(Boolean) as string[]);
    const patterns = entries.map((e) => e.pattern).filter(Boolean).map((g) => patternToRegExp(g as string));

    const orphans = readdirSync(dir)
      .filter((name) => name !== SELF)
      .filter((name) => !exact.has(name))
      .filter((name) => !patterns.some((re) => re.test(name)));

    expect(orphans, 'present in the project folder and declared nowhere').toEqual([]);
  });

  it('every entry carries a role and a deploy target', () => {
    const roles = new Set(Object.keys(manifest.roles || {}));
    const targets = new Set(Object.keys(manifest.deployTargets || {}));
    const bad = entries.filter((e) => !roles.has(String(e.role)) || !targets.has(String(e.deployTo)));
    expect(bad, 'an entry with no role or no deploy target cannot be audited').toEqual([]);
  });

  it('an entry declares a path OR a pattern, never both and never neither', () => {
    const bad = entries.filter((e) => Boolean(e.path) === Boolean(e.pattern));
    expect(bad, 'ambiguous entry').toEqual([]);
  });
});

describe('WHAT MAY BE WRITTEN INTO A CLIENT REPOSITORY IS ENUMERATED', () => {
  /**
   * The engine must not write to a client codeline except deliberately. This asserts the
   * two halves agree: anything a project file claims to deploy must appear in the
   * codelineArtifacts allow-list, and nothing may deploy without being listed there.
   */
  it.each(found)('$name — every codeline-bound file is in the allow-list', ({ manifest }) => {
    const allowed = new Set(Object.keys(manifest.codelineArtifacts || {}));
    expect(allowed.size, 'no codelineArtifacts allow-list declared').toBeGreaterThan(0);

    const deployed = Object.values(manifest.files || {})
      .filter((e: any) => e.deployTo === 'codeline')
      .map((e: any) => String(e.path).split('/').pop());

    const notAllowed = deployed.filter((f) => !allowed.has(String(f)));
    expect(notAllowed, 'a project file claims to deploy to a codeline but is not in the allow-list').toEqual([]);
  });

  it.each(found)('$name — main-only files never appear in the allow-list', ({ manifest }) => {
    const allowed = new Set(Object.keys(manifest.codelineArtifacts || {}));
    const leaked = Object.values(manifest.files || {})
      .filter((e: any) => e.deployTo === 'main-only' && e.path)
      .map((e: any) => String(e.path).split('/').pop())
      .filter((f) => allowed.has(String(f)));
    expect(leaked, 'declared main-only yet listed as a codeline artifact — contradictory').toEqual([]);
  });
});
