/**
 * A CODELINE'S COMPLETED AGENTS AND PROMPTS ARE REUSED, NOT REGENERATED EVERY RUN.
 *
 * Operator, 2026-09-05: "it does not have to be generated again and again once we stabilize the
 * pipeline I want it to be tagged to a codeline and reused for the codeline" and "ensure cache for
 * codeline agents/profile and prompts can be saved after this run and not regenerated unless there
 * is an override for the codeline to regenerate".
 *
 * WHAT IT COSTS TODAY. Measured on the live 2026-09-05 run: 39 templates regenerated by a model
 * and each reviewed by a second one — prompt-builder $1.25 over 25 calls plus prompt-review $1.51
 * over 16 = $2.76, 36% of the run's spend before the pipeline did any work of its own. The roster
 * is re-derived alongside them: a paid roster-specialiser call and ~13 minutes of wall clock. None
 * of it changes between two runs against the same codeline with the same templates.
 *
 * THE PRECEDENT IS ALREADY IN THIS FILE'S SUBJECT. pre-run-reset.sh keeps the roster on a RESUMED
 * run, and the comment above that branch records exactly why: re-deriving cost a paid specialiser
 * call, produced a roster differing from the reviewed one, and invalidated every roster-keyed
 * prompt — 17 of 39 regenerated on the 2026-09-01 resume for no other reason. This generalises
 * that same judgement from "a resumed run" to "the same codeline".
 *
 * WHY THE CLEAN-SLATE RULE STILL HOLDS. "No prior run artefacts, ever" exists because a roster
 * derived for ANOTHER context silently mis-assigns work — a stale survey matched by codeline name,
 * a roster naming agents that no longer exist. So retention is not "keep whatever is lying there".
 * It is conditional, and every condition below is a failure this repo has already paid for:
 *
 *   - the assets must be marked COMPLETE. Operator: "if prompts complete this run we consider for
 *     the cache." A run that died mid-provisioning leaves a partial set, and reusing it would make
 *     a half-provisioned run look finished.
 *   - the marker must name THIS codeline. Cross-codeline reuse is the stale-survey defect with a
 *     different filename.
 *   - an explicit override must force regeneration, or a stabilised cache becomes a trap the
 *     operator cannot escape.
 *
 * Absent any marker, behaviour is unchanged: delete and re-derive. That is the safe default and
 * the one every existing test already asserts.
 */
import { describe, it, expect, afterAll } from 'vitest';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const RESET = join(__dirname, '../../../orchestrations/scripts/pre-run-reset.sh');
const dirs: string[] = [];
afterAll(() => { for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true }); });

const CODELINE = 'next.gotransit.com';

/**
 * A project config dir shaped like a real one AFTER a completed run: a minted roster, the
 * profiles that go with it, provisioned prompts and the prompt cache.
 */
function project(opts: { marker?: object | null } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'codeline-assets-'));
  dirs.push(root);
  const cfg = join(root, 'projects', 'metrolinx');
  mkdirSync(join(cfg, 'prompts'), { recursive: true });
  mkdirSync(join(cfg, '.prompt-cache'), { recursive: true });

  writeFileSync(join(cfg, 'roster.json'),
    JSON.stringify({ agents: { 'checkout-forms-engineer': { role: 'implementer' } } }));
  for (const f of ['agent-profiles.json', 'project-roles.json', 'project-profiles.json',
    'project-investigators.json']) {
    writeFileSync(join(cfg, f), JSON.stringify({ from: 'the completed run' }));
  }
  writeFileSync(join(cfg, 'prompts', 'roster-review.json'), JSON.stringify({ body: 'REUSED BODY' }));
  writeFileSync(join(cfg, '.prompt-cache', 'roster-review.json'),
    JSON.stringify({ base: 'aaa', roles: 'bbb', reviewed: true }));

  if (opts.marker !== null) {
    writeFileSync(join(cfg, '.prompt-cache', '.complete'),
      JSON.stringify(opts.marker ?? { codeline: CODELINE, provisioned: 39, refused: 0 }));
  }
  return { root, cfg };
}

function runReset(cfg: string, env: Record<string, string> = {}) {
  const logDir = mkdtempSync(join(tmpdir(), 'cl-logs-'));
  dirs.push(logDir);
  const prd = join(logDir, 'prd.json');
  writeFileSync(prd, JSON.stringify({ stories: [] }));
  let out = '';
  try {
    out = execFileSync('bash', [RESET, '--prd', prd, '--log-dir', logDir], {
      encoding: 'utf8', timeout: 120_000,
      env: {
        ...process.env,
        EPAM_PROJECT_CONFIG_DIR: cfg,
        JIRA_CODELINE_ROOT: '',
        ...env,
      },
    });
  } catch (e: any) { out = `${e.stdout || ''}${e.stderr || ''}`; }
  return out;
}

const kept = (cfg: string, rel: string) => existsSync(join(cfg, rel));

describe('a codeline whose assets completed', () => {
  it('KEEPS the roster — it is not re-derived from canonical', () => {
    const { cfg } = project();
    runReset(cfg, { EPAM_CODELINE_ID: CODELINE });
    expect(kept(cfg, 'roster.json'), [
      'the completed roster was cleared, so the run re-derives it: a paid roster-specialiser call',
      'and ~13 minutes, producing agents this codeline already had.',
    ].join('\n')).toBe(true);
  });

  it.each(['agent-profiles.json', 'project-roles.json', 'project-profiles.json',
    'project-investigators.json'])('KEEPS %s', (f) => {
    const { cfg } = project();
    runReset(cfg, { EPAM_CODELINE_ID: CODELINE });
    expect(kept(cfg, f), `${f} was cleared, so the mint must run again to rebuild it`).toBe(true);
  });

  it('KEEPS the provisioned prompts, with their content intact', () => {
    const { cfg } = project();
    runReset(cfg, { EPAM_CODELINE_ID: CODELINE });
    expect(kept(cfg, 'prompts/roster-review.json'),
      'the provisioned prompts were wiped, so all 39 are regenerated and re-reviewed').toBe(true);
    expect(readFileSync(join(cfg, 'prompts/roster-review.json'), 'utf8'),
      'the prompt file survived but its content did not').toContain('REUSED BODY');
  });

  it('KEEPS the prompt cache', () => {
    const { cfg } = project();
    runReset(cfg, { EPAM_CODELINE_ID: CODELINE });
    expect(kept(cfg, '.prompt-cache/roster-review.json')).toBe(true);
  });

  it('says so, rather than reusing silently', () => {
    // A run that silently reused a previous run's agents is indistinguishable from one that
    // minted them. The operator approves a roster at pause 1; they must know which they are seeing.
    const out = runReset(project().cfg, { EPAM_CODELINE_ID: CODELINE });
    expect(out, 'nothing in the output says the assets were reused rather than re-derived')
      .toMatch(/reus|kept|carried over/i);
  });
});

describe('the conditions on that reuse — each one a defect this repo has paid for', () => {
  it('NO MARKER — assets are cleared, exactly as today', () => {
    // The safe default, and what every existing pre-run-reset test asserts. A run that died
    // mid-provisioning leaves no marker, so its partial set is never inherited.
    const { cfg } = project({ marker: null });
    runReset(cfg, { EPAM_CODELINE_ID: CODELINE });
    expect(kept(cfg, 'roster.json'),
      'assets with no completion marker were retained — a half-provisioned run would look finished')
      .toBe(false);
  });

  it('INCOMPLETE MARKER — a run that refused prompts is not cache-eligible', () => {
    // "if prompts complete this run we consider for the cache". Refusals mean the set is partial.
    const { cfg } = project({ marker: { codeline: CODELINE, provisioned: 31, refused: 8 } });
    runReset(cfg, { EPAM_CODELINE_ID: CODELINE });
    expect(kept(cfg, 'roster.json'),
      'assets from a run with refused prompts were reused; the missing ones never regenerate')
      .toBe(false);
  });

  it('DIFFERENT CODELINE — no cross-codeline reuse', () => {
    // The stale-survey defect with a different filename: assets specialised for one codeline
    // silently applied to another.
    const { cfg } = project({ marker: { codeline: 'next.upexpress.com', provisioned: 39, refused: 0 } });
    runReset(cfg, { EPAM_CODELINE_ID: CODELINE });
    expect(kept(cfg, 'roster.json'),
      "another codeline's roster was reused for this one").toBe(false);
  });

  it('OVERRIDE — the operator can force regeneration', () => {
    const { cfg } = project();
    runReset(cfg, { EPAM_CODELINE_ID: CODELINE, EPAM_REGENERATE_CODELINE_ASSETS: '1' });
    expect(kept(cfg, 'roster.json'),
      'the override did not force regeneration, so a stabilised cache is a trap with no exit')
      .toBe(false);
  });

  it('the override is REPORTED, so a re-derivation is never a mystery', () => {
    const out = runReset(project().cfg,
      { EPAM_CODELINE_ID: CODELINE, EPAM_REGENERATE_CODELINE_ASSETS: '1' });
    expect(out).toMatch(/regenerat|override/i);
  });

  it('NO CODELINE DECLARED — cannot prove a match, so it clears', () => {
    // Unable to prove the assets belong to this run is not the same as proving they do. The
    // unsafe direction here is reuse.
    const { cfg } = project();
    runReset(cfg, { EPAM_CODELINE_ID: '' });
    expect(kept(cfg, 'roster.json'),
      'assets were reused without any codeline to match them against').toBe(false);
  });

  it('a CORRUPT marker clears, never reuses', () => {
    const root = mkdtempSync(join(tmpdir(), 'codeline-corrupt-'));
    dirs.push(root);
    const cfg = join(root, 'projects', 'metrolinx');
    mkdirSync(join(cfg, '.prompt-cache'), { recursive: true });
    mkdirSync(join(cfg, 'prompts'), { recursive: true });
    writeFileSync(join(cfg, 'roster.json'), '{"agents":{}}');
    writeFileSync(join(cfg, '.prompt-cache', '.complete'), '{"codeline":');   // truncated
    runReset(cfg, { EPAM_CODELINE_ID: CODELINE });
    expect(kept(cfg, 'roster.json'),
      'an unreadable marker was treated as permission to reuse').toBe(false);
  });
});
