/**
 * A PROJECT'S VERIFICATION DECLARATION SURVIVES THE CODELINE RESET.
 *
 * .epam/ is UNTRACKED in a client codeline, and the brownfield reset runs `git clean -fd`, so the
 * whole directory is destroyed before every run and regenerated by detection. Anything declared
 * there by hand lives exactly one run.
 *
 * That is how the clock pin was lost. clockInstant and clockPinnedCommand were written into
 * <codeline>/.epam/verification.json, the run wiped and regenerated the file, the keys were gone,
 * and the suite ran unpinned — so AMSD-1919 met the same wall-clock failure the pin exists to
 * remove. The engine was correct and tested; the declaration simply could not reach it.
 *
 * The merge in _epam_write_verification_manifest already prefers an EXISTING key over a detected
 * one — good, and useless here, because after a reset nothing exists to prefer.
 *
 * So a project declares verification overrides in ITS OWN config dir, which no codeline reset can
 * touch, and the generator merges them. Precedence, lowest to highest:
 *
 *     detected  <  project-declared  <  hand-tuned in the codeline
 *
 * Detection still fills in whatever nobody declared; an operator editing the codeline copy for one
 * run still wins for that run; and what the project declares comes back after every reset.
 */
import { describe, it, expect, afterAll } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const SCRIPTS = join(__dirname, '../../../orchestrations/scripts');
const dirs: string[] = [];
afterAll(() => { for (const d of dirs) rmSync(d, { recursive: true, force: true }); });

/** A node repo the plugin can detect (package.json scripts), plus an optional project config. */
function fixture(opts: { projectDecl?: Record<string, unknown>; codelineExisting?: Record<string, unknown> }) {
  const root = mkdtempSync(join(tmpdir(), 'vdecl-'));
  dirs.push(root);
  const repo = join(root, 'codeline');
  const cfg = join(root, 'project-config');
  mkdirSync(repo, { recursive: true });
  mkdirSync(cfg, { recursive: true });
  writeFileSync(join(repo, 'package.json'), JSON.stringify({
    name: 'c', scripts: { test: 'jest', 'check-types': 'tsc --noEmit' },
  }, null, 2));
  if (opts.projectDecl) {
    writeFileSync(join(cfg, 'verification.json'), JSON.stringify(opts.projectDecl, null, 2));
  }
  if (opts.codelineExisting) {
    mkdirSync(join(repo, '.epam'), { recursive: true });
    writeFileSync(join(repo, '.epam', 'verification.json'),
      JSON.stringify(opts.codelineExisting, null, 2));
  }
  return { root, repo, cfg };
}

/** Runs the REAL generator, then reads the manifest it wrote. */
function generate(f: { repo: string; cfg: string }) {
  const src = readFileSync(join(SCRIPTS, 'lib/git-ops.sh'), 'utf8');
  const start = src.indexOf('_epam_write_verification_manifest() {');
  const end = src.indexOf('\n}\n', start) + 3;
  expect(start, 'the generator was not found in git-ops.sh').toBeGreaterThan(0);
  const dir = mkdtempSync(join(tmpdir(), 'vgen-'));
  dirs.push(dir);
  const drive = join(dir, 'drive.sh');
  writeFileSync(drive, ['#!/usr/bin/env bash', 'set -uo pipefail',
    src.slice(start, end),
    `_epam_write_verification_manifest ${JSON.stringify(f.repo)}`].join('\n'));
  try {
    execFileSync('bash', [drive], { encoding: 'utf8', timeout: 60_000,
      env: { ...process.env,
             AUTOMATION_DIR: join(SCRIPTS, '..'),
             EPAM_PROJECT_CONFIG_DIR: f.cfg,
             NODE_BIN: process.execPath } });
  } catch { /* the generator is deliberately non-fatal */ }
  const out = join(f.repo, '.epam', 'verification.json');
  return existsSync(out) ? JSON.parse(readFileSync(out, 'utf8')) : null;
}

describe('a project-declared verification override', () => {
  it('GUARD: detection still works when the project declares nothing', () => {
    const m = generate(fixture({}));
    expect(m, 'no manifest was generated at all').toBeTruthy();
    expect(m.test?.command, 'detection stopped finding the test command').toBeTruthy();
  });

  it('SURVIVES A RESET — the declaration comes from the project config, not the codeline', () => {
    // The codeline has NO .epam at all, exactly as it is after `git clean -fd`.
    const m = generate(fixture({
      projectDecl: { test: { clockInstant: '2026-01-15T15:00:00Z',
                             clockPinnedCommand: 'npm run test -- --setupFiles={setupFile}' } },
    }));
    expect(m.test?.clockInstant,
      'the project declared a clock and the generated manifest does not carry it — the pin can '
      + 'never reach the engine, and the suite runs on the wall clock again')
      .toBe('2026-01-15T15:00:00Z');
    expect(m.test?.clockPinnedCommand).toBe('npm run test -- --setupFiles={setupFile}');
  });

  it('does not clobber what detection found — both are present', () => {
    const m = generate(fixture({
      projectDecl: { test: { clockInstant: '2026-01-15T15:00:00Z' } },
    }));
    expect(m.test?.command, 'the declaration replaced the detected command instead of adding to it')
      .toBeTruthy();
    expect(m.test?.clockInstant).toBe('2026-01-15T15:00:00Z');
  });

  it('a HAND-TUNED codeline value still wins for that run', () => {
    // An operator editing the codeline copy mid-run must not be overwritten by the project's
    // default — the same precedence the existing merge already grants over detection.
    const m = generate(fixture({
      projectDecl: { test: { clockInstant: '2026-01-15T15:00:00Z' } },
      codelineExisting: { test: { command: 'npm run test', clockInstant: '2030-07-04T00:00:00Z' } },
    }));
    expect(m.test?.clockInstant, 'the project default overwrote a hand-tuned codeline value')
      .toBe('2030-07-04T00:00:00Z');
  });

  it('a project declaring nothing for a section leaves that section as detected', () => {
    const m = generate(fixture({ projectDecl: { test: { clockInstant: '2026-01-15T15:00:00Z' } } }));
    expect(m.typecheck?.command, 'declaring a test override disturbed the typecheck section')
      .toBeTruthy();
  });
});
