/**
 * A TIMEOUT ON ONE PROMPT KILLED THE MINT AND EVERYTHING IT HAD ALREADY DONE.
 *
 * buildProjectPrompts retries each prompt up to `attempts` times: a generated prompt that drops a
 * placeholder is REFUSED, the reason is fed back, and the next attempt corrects it. That loop only
 * covers a prompt that came back WRONG. A call that never came back at all —
 *
 *     const body = String((await runText(prompt, { id, attempt })) || '');
 *
 * — throws straight out of the loop, out of buildProjectPrompts, and out of the mint step.
 *
 * Live 2026-08-17, run 20260817T185759Z: "prompt runner timed out after 360000ms", and with it
 * went the estate survey, the minted roster, the story assignment and 12 already-generated prompts
 * — 30 minutes into the first run that had cleared every earlier stage correctly. One slow call
 * out of 51 destroyed all of it.
 *
 * A timeout is the most retryable failure there is: nothing is known to be wrong with the request,
 * the call simply did not finish. It should cost one attempt, exactly as a refusal does.
 *
 * IT MUST STAY DISTINGUISHABLE. "refused: dropped __STORY_ID__" and "the call did not come back"
 * are fixed in different places — one is a prompt-contract problem, the other a budget or provider
 * problem — so the log and the final error must not collapse them into one word.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const ROOT = join(__dirname, '../../..');
const TEMPLATES = join(ROOT, 'orchestrations/prompts/templates');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { buildProjectPrompts } = require(join(ROOT, 'orchestrations/scripts/lib/project-prompt-builder.js'));

let work: string;
let projectDir: string;
let bootstrapFile: string;

/** One tiny template to generate, so the test exercises the loop and not 51 model calls. */
const TEMPLATE_ID = 'blocker-discipline';

beforeEach(() => {
  work = mkdtempSync(join(tmpdir(), 'ppb-'));
  projectDir = join(work, 'project');
  mkdirSync(join(projectDir, 'prompts'), { recursive: true });
  bootstrapFile = join(work, 'bootstrap.json');
  // copyVerbatim carries the generator's own prompt: it cannot be generated by itself.
  writeFileSync(bootstrapFile, JSON.stringify({
    copyVerbatim: ['project-prompt-generation'],
    generated: [TEMPLATE_ID],
  }));
});
afterEach(() => { rmSync(work, { recursive: true, force: true }); });

/**
 * A generated body that satisfies the template's contract.
 *
 * The template's OWN text trivially satisfies it: every placeholder present, none invented. A
 * template carries either `body` (a string) or `bodies` (a map of named blocks) — reading only
 * `body` produced an empty string here and made every attempt fail for the wrong reason.
 */
function goodBody(): string {
  const t = JSON.parse(readFileSync(join(TEMPLATES, `${TEMPLATE_ID}.json`), 'utf8'));
  if (typeof t.body === 'string' && t.body) return t.body;
  return Object.values(t.bodies || {}).filter((v) => typeof v === 'string').join('\n');
}

function build(runText: (p: string, meta: any) => Promise<string>, log: string[] = []) {
  return buildProjectPrompts({
    templatesDir: TEMPLATES,
    bootstrapFile,
    projectConfigDir: projectDir,
    runText,
    projectContext: 'ctx',
    codelineContext: 'cl',
    mintedRoles: 'roles',
    attempts: 3,
    mode: 'generate',
    log: (m: string) => log.push(m),
  });
}

describe('one slow prompt destroyed thirty minutes of work', () => {
  it('A TIMEOUT COSTS ONE ATTEMPT, not the whole run', async () => {
    let n = 0;
    const log: string[] = [];
    const out = await build(async () => {
      n += 1;
      if (n === 1) throw new Error('prompt runner timed out after 360000ms');
      return goodBody();
    }, log);

    expect(n, 'the timeout was not retried').toBe(2);
    expect(out.generated, 'the prompt was never installed after recovering').toContain(TEMPLATE_ID);
    expect(existsSync(join(projectDir, 'prompts', `${TEMPLATE_ID}.json`))).toBe(true);
  });

  it('the log says the CALL failed, not that the prompt was refused', async () => {
    // Fixed in different places: a refusal is a prompt-contract problem, a timeout is a budget or
    // provider problem. Collapsing them sends the reader to the wrong file.
    const log: string[] = [];
    let n = 0;
    await build(async () => {
      n += 1;
      if (n === 1) throw new Error('prompt runner timed out after 360000ms');
      return goodBody();
    }, log);

    const line = log.find((l) => /timed out/.test(l));
    expect(line, 'the timeout is invisible in the log').toBeTruthy();
    expect(line, 'a failed call was reported as a contract refusal').not.toMatch(/refused:/);
  });

  it('the retry is TOLD the call failed — it must not read as a content complaint', async () => {
    const seen: string[] = [];
    let n = 0;
    await build(async (prompt: string) => {
      seen.push(prompt);
      n += 1;
      if (n === 1) throw new Error('prompt runner timed out after 360000ms');
      return goodBody();
    });
    expect(seen[1], 'the second attempt was not told what happened to the first')
      .toMatch(/timed out|did not (come back|complete)/i);
  });

  it('EXHAUSTING the attempts still fails, naming the call failure', async () => {
    // The guard must not swallow a genuinely broken provider into an endless quiet retry.
    let n = 0;
    await expect(build(async () => {
      n += 1;
      throw new Error('prompt runner timed out after 360000ms');
    })).rejects.toThrow(/timed out/);
    expect(n, 'the attempt budget was not honoured').toBe(3);
  });

  it('a CONTRACT refusal still behaves exactly as before', async () => {
    // The pre-existing path must not change: a body that fails the contract is refused and retried.
    // An EMPTY body, rather than a missing placeholder — this template declares none, so "no
    // placeholders" satisfies its contract and would have proved nothing.
    let n = 0;
    const log: string[] = [];
    const out = await build(async () => {
      n += 1;
      return n === 1 ? '' : goodBody();
    }, log);
    expect(n).toBe(2);
    expect(out.generated).toContain(TEMPLATE_ID);
    expect(log.some((l) => /refused:/.test(l)), 'a dropped placeholder stopped being a refusal')
      .toBe(true);
  });

  it('a first-attempt success still costs exactly one call', async () => {
    let n = 0;
    await build(async () => { n += 1; return goodBody(); });
    expect(n, 'a good prompt was retried anyway').toBe(1);
  });
});
