// STALENESS DETECTOR — deliberately NOT in the guard set.
//
// The guard suite's value is that red means "something broke just now". This check is red for a
// legitimate, expected reason in the window between a template change and the next mint: project
// prompts are regenerated by the pipeline, not by hand, so a corrected template does not reach a
// project's copies until that project next runs. Keeping it in the guard set would mean a red
// suite that everyone learns to ignore.
//
// The DURABLE assertion — that the TEMPLATE states the contract its parser enforces — stays in
// the-prompt-reviewer-was-never-executed.test.ts, in the guard set, where it belongs.
//
// Run this deliberately to find project copies that predate a template fix.
import { describe, it, expect } from 'vitest';
import { join } from 'node:path';

const ROOT = join(__dirname, '../../..');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fs = require('node:fs');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const promptsLib = require(join(ROOT, 'orchestrations/scripts/lib/prompt-library.js'));

const parserSrc: string = fs.readFileSync(join(ROOT, 'orchestrations/scripts/lib/prompt-review.js'), 'utf8');
const TAG = parserSrc.match(/<(\w+)>\(\[\\s\\S\]\*\?\)<\\\/\1>/)?.[1];
const KEY = parserSrc.match(/verdict\.(\w+)/)?.[1];

describe('provisioned reviewer prompts carry the contract', () => {
  it('every provisioned copy asks for it too — generation must not drop the contract', () => {
    const projects = join(ROOT, 'orchestrations/projects');
    if (!fs.existsSync(projects)) return;
    const checked: string[] = [];
    for (const name of fs.readdirSync(projects)) {
      const file = promptsLib.projectPromptPath('prompt-review', join(projects, name));
      if (!fs.existsSync(file)) continue;
      const body: string = JSON.parse(fs.readFileSync(file, 'utf8')).body ?? '';
      checked.push(name);
      expect(body, `${name}: provisioned reviewer prompt omits <${TAG}>; its reviews cannot be parsed`)
        .toContain(`<${TAG}>`);
      expect(body, `${name}: provisioned reviewer prompt omits '${KEY}'`).toContain(KEY!);
    }
    expect(checked.length, 'no provisioned reviewer prompt was found; this test proved nothing').toBeGreaterThan(0);
  });
});
