/**
 * EVERY RUN STARTS FROM THE CANONICAL BASE ROSTER.
 *
 * Agent identities are generated per project now. A generated roster that survives into the
 * next run is a mutated base — and because the merge is additive by design (so a brief that
 * accumulated skill notes is never rewritten), a second mint simply ADDS to the first.
 *
 * Live 2026-08-07, two runs, five roles left behind:
 *   contentful-cms-engineer, preview-auth-specialist          <- run 1, wrong vendor
 *   nextjs-preview-engineer                                    <- both runs
 *   contentstack-sdk-engineer, contentstack-preview-config-specialist  <- run 2
 *
 * Aggregating a roster over runs is not permitted. This is enforced in pre-run-reset.sh
 * rather than in the mint, so no launcher can skip it and the base is clean even for a run
 * that never reaches the mint.
 *
 * KB-<role>.md is deliberately NOT cleared: profiles.json is ephemeral, the per-agent KB
 * files are the cross-run knowledge store (879c705).
 */
import { describe, it, expect, afterAll } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const RESET = join(__dirname, '../../../orchestrations/scripts/pre-run-reset.sh');
const RESET_SRC = readFileSync(RESET, 'utf8');

const dirs: string[] = [];
afterAll(() => { for (const d of dirs) rmSync(d, { recursive: true, force: true }); });

/** Run ONLY the roster-reset block, extracted verbatim from the real script. */
function runRosterReset(projectCfgDir: string, agentsDir: string) {
  const start = RESET_SRC.indexOf('_ROSTER_CLEARED=0');
  const end = RESET_SRC.indexOf('# Clear stale lock files');
  const block = RESET_SRC.slice(start, end === -1 ? undefined : end);
  expect(block.length, 'the roster-reset block is gone from pre-run-reset.sh').toBeGreaterThan(200);

  const script =
    `set +e\n` +
    `info() { echo "$*"; }\n` +
    `export EPAM_PROJECT_CONFIG_DIR=${JSON.stringify(projectCfgDir)}\n` +
    `export EPAM_AGENTS_DIR=${JSON.stringify(agentsDir)}\n` +
    block;
  return spawnSync('bash', ['-c', script], { encoding: 'utf8' });
}

function estate() {
  const root = mkdtempSync(join(tmpdir(), 'ephem-')); dirs.push(root);
  const agents = join(root, 'agents');
  mkdirSync(agents, { recursive: true });
  mkdirSync(join(root, 'scripts'), { recursive: true });
  writeFileSync(join(agents, 'profiles.json.original'), JSON.stringify({ 'review-agent': 'canonical' }, null, 2));
  writeFileSync(join(agents, 'profiles.json'), JSON.stringify({
    'review-agent': 'canonical', 'a-generated-engineer': 'minted last run',
  }, null, 2));
  writeFileSync(join(agents, 'KB-a-generated-engineer.md'), '# learned last run');

  const cfg = join(root, 'project'); mkdirSync(cfg, { recursive: true });
  writeFileSync(join(cfg, 'project-roles.json'), JSON.stringify({ roles: ['a-generated-engineer'] }));
  writeFileSync(join(cfg, 'agent-profiles.json'), JSON.stringify({ profiles: { 'a-generated-engineer': 'brief' } }));
  return { root, agents, cfg };
}

describe('the previous run\'s generated roster does not survive', () => {
  it('the live roster is restored to the canonical base', () => {
    const { agents, cfg } = estate();
    runRosterReset(cfg, agents);
    const after = JSON.parse(readFileSync(join(agents, 'profiles.json'), 'utf8'));
    expect(
      Object.keys(after),
      'a role generated by a previous run is still in the roster this run starts from',
    ).toEqual(['review-agent']);
  });

  it('the generated role registry is cleared', () => {
    const { agents, cfg } = estate();
    runRosterReset(cfg, agents);
    expect(existsSync(join(cfg, 'project-roles.json'))).toBe(false);
  });

  it('the stored briefs are cleared', () => {
    const { agents, cfg } = estate();
    runRosterReset(cfg, agents);
    expect(existsSync(join(cfg, 'agent-profiles.json'))).toBe(false);
  });

  it('two runs cannot aggregate — the second starts from the same base as the first', () => {
    const { agents, cfg } = estate();
    runRosterReset(cfg, agents);
    // a run mints something
    const live = JSON.parse(readFileSync(join(agents, 'profiles.json'), 'utf8'));
    live['another-generated-engineer'] = 'minted this run';
    writeFileSync(join(agents, 'profiles.json'), JSON.stringify(live, null, 2));
    // next run resets again
    runRosterReset(cfg, agents);
    expect(
      Object.keys(JSON.parse(readFileSync(join(agents, 'profiles.json'), 'utf8'))),
      'roles accumulated across runs',
    ).toEqual(['review-agent']);
  });
});

describe('cross-run agent KNOWLEDGE still persists', () => {
  it('KB-<role>.md is not deleted — it is the cross-run store', () => {
    const { agents, cfg } = estate();
    runRosterReset(cfg, agents);
    expect(
      existsSync(join(agents, 'KB-a-generated-engineer.md')),
      'the per-agent knowledge store was wiped along with the ephemeral roster',
    ).toBe(true);
  });
});

describe('it is safe when there is nothing to clear', () => {
  it('a project with no generated roster resets without error', () => {
    const { agents } = estate();
    const cfg = mkdtempSync(join(tmpdir(), 'empty-cfg-')); dirs.push(cfg);
    const r = runRosterReset(cfg, agents);
    expect(r.status).toBe(0);
  });
});
