#!/usr/bin/env bats
# ─────────────────────────────────────────────────────────────────────────────
# A SEAM THAT RENDERS FROM THE PROJECT LAYER MUST HAVE A PROJECT COPY TO RENDER.
#
# THIS TEST EXISTS BECAUSE ITS ABSENCE COST A LAUNCH. Routing sends every seam-declared prompt to
# this project's copy with no fallback, which is correct. metrolinx had no copy of
# codeline-discovery, which runs during Jira INGEST — before the mint that generates copies — so
# the run aborted at its first step.
#
# The check that let it through asked the wrong question. It derived the bootstrap set from the
# MINT's own agent sequence, cut at prompt-builder, and that is structurally blind to every stage
# running BEFORE the mint: ingest, discovery, the spec pass. It then verified that 23 of 24 prompts
# rendered — which proves files exist on disk, and says nothing about whether one is needed before
# it is produced.
#
# So this asserts the property that actually protects a run, and needs no notion of ordering at
# all: if a seam renders from the project layer, every project must already hold that prompt.
# Anything that cannot — because it runs before the layer exists — declares layer: "bootstrap" on
# its seam and says why.
# ─────────────────────────────────────────────────────────────────────────────

setup() {
    REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../../.." && pwd)"
    SCRIPTS="$REPO_ROOT/orchestrations/scripts"
    REGISTRY="$REPO_ROOT/orchestrations/agents/invocation-profiles.json"
    PROJECTS="$REPO_ROOT/orchestrations/projects"
    NODE="${NODE_BIN:-$HOME/.nvm/versions/node/v20.20.0/bin/node}"
    command -v "$NODE" >/dev/null 2>&1 || NODE=node
}

# Seam templates the renderer will route to the PROJECT layer — asked of the renderer itself, so
# the test and the code cannot disagree about which those are.
project_layer_templates() {
    "$NODE" -e '
      const fs = require("fs");
      const reg = require(process.argv[1]).profiles || {};
      const out = new Set();
      (function w(o) { for (const k in o) { const v = o[k];
        if (v && typeof v === "object") {
          if (v.template && v.layer !== "bootstrap") out.add(v.template);
          w(v); } } }(reg));
      process.stdout.write([...out].sort().join("\n"));
    ' "$REGISTRY"
}

@test "the check is real — there are project-layer seam templates to check" {
    run project_layer_templates
    [ -n "$output" ]
    [ "$(printf '%s\n' "$output" | grep -c .)" -ge 10 ]
}

@test "EVERY project-layer seam prompt is PROVISIONED by the mint" {
    # NOT "exists in the repo". pre-run-reset.sh:620 does `rm -rf <project>/prompts` on every
    # launch — project prompts are run OUTPUTS, regenerated by the mint — so a committed copy
    # only proves that some previous run produced one. Asserting existence would pass on stale
    # artefacts and fail on a fresh project, and it says nothing about the case that broke the
    # launch: a prompt needed BEFORE the mint has produced it.
    #
    # The invariant that holds regardless of repo state: anything the renderer routes to the
    # project layer must be in the set the mint provisions. Anything that cannot wait for the
    # mint declares layer: "bootstrap".
    missing=$("$NODE" -e '
      const fs = require("fs"), path = require("path");
      const m = require(process.argv[1]);
      // copyVerbatim COUNTS AS PROVISIONED. The mint installs those byte-identical — they are
      // the prompts that generate prompts, and generating them would require themselves. A copy
      // is still a copy on disk when the seam reaches for it.
      const bootstrapDoc = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
      const provisioned = new Set([
        ...(bootstrapDoc.copyVerbatim || []),
        ...m.provisioningList({
          bootstrap: bootstrapDoc,
          registry:  JSON.parse(fs.readFileSync(process.argv[3], "utf8")),
          templateExists: (id) => fs.existsSync(path.join(process.argv[4], id + ".json")),
        }),
      ]);
      const reg = JSON.parse(fs.readFileSync(process.argv[3], "utf8")).profiles || {};
      const bad = [];
      (function w(o) { for (const k in o) { const v = o[k];
        if (v && typeof v === "object") {
          if (v.template && v.layer !== "bootstrap" && !provisioned.has(v.template))
            bad.push(`${k} -> ${v.template}`);
          w(v); } } }(reg));
      process.stdout.write([...new Set(bad)].join("\n"));
    ' "$SCRIPTS/lib/project-prompt-builder.js" \
      "$REPO_ROOT/orchestrations/prompts/bootstrap.json" \
      "$REGISTRY" \
      "$REPO_ROOT/orchestrations/prompts/templates")

    [ -z "$missing" ] || {
        echo "seams route to a project prompt the mint never provisions:"
        echo "$missing"
        echo ""
        echo "Each is a run that aborts the moment that seam is reached. Either provision it, or"
        echo "— if it runs before the mint — declare layer: \"bootstrap\" on its seam and say why."
        false
    }
}

@test "NOTHING RENDERED DURING INGEST routes to the project layer" {
    # The case that cost the launch, asserted directly. Ingest runs before the mint and after
    # pre-run-reset has emptied prompts/, so every prompt it renders must be bootstrap. Derived
    # by reading what ingest actually invokes — my first attempt derived the bootstrap set from
    # the MINT's agent sequence, which is structurally blind to every stage before it.
    ids=$("$NODE" -e '
      const fs = require("fs");
      const files = ["lib/codeline-discovery.js", "lib/ac-gate.js"]
        .map((f) => process.argv[1] + "/" + f).filter((f) => fs.existsSync(f));
      const ids = new Set();
      for (const f of files) {
        const src = fs.readFileSync(f, "utf8");
        for (const m of src.matchAll(/renderEngineTemplate\(.([a-z0-9-]+)./g)) ids.add(m[1]);
      }
      const reg = JSON.parse(fs.readFileSync(process.argv[2], "utf8")).profiles || {};
      const bad = [];
      (function w(o) { for (const k in o) { const v = o[k];
        if (v && typeof v === "object") {
          if (v.template && ids.has(v.template) && v.layer !== "bootstrap") bad.push(v.template);
          w(v); } } }(reg));
      process.stdout.write([...new Set(bad)].join(" "));
    ' "$SCRIPTS" "$REGISTRY")
    [ -z "$ids" ] || {
        echo "rendered during ingest but not declared bootstrap: $ids"
        echo "prompts/ is empty at that point — the run aborts on the first one."
        false
    }
}

@test "every bootstrap declaration STATES WHY it cannot be a project prompt" {
    # Otherwise 'bootstrap' becomes the way to silence this test, and the next reader cannot tell
    # a real ordering constraint from an unprovisioned prompt.
    run "$NODE" -e '
      const reg = require(process.argv[1]).profiles || {};
      const bad = [];
      (function w(o) { for (const k in o) { const v = o[k];
        if (v && typeof v === "object") {
          if (v.layer === "bootstrap" && !String(v._why_bootstrap || "").trim()) bad.push(k);
          w(v); } } }(reg));
      process.stdout.write(bad.join(" "));' "$REGISTRY"
    [ -z "$output" ] || { echo "bootstrap declared with no reason: $output"; false; }
}
