# generate-env-example.sh — .env.example is GENERATED, never hand-maintained.
#
# The hand-maintained version went stale in both directions: root .env.example never mentioned
# EPAM_PROVIDER_SET, JIRA_TOKEN, or the openrouter set's own required OPENROUTER_API_KEY /
# MINIMAX_API_KEY (all declared in provider-sets.json, none reflected in what an operator was told
# to copy and fill in) — and launch-dashboard/.env.example kept saying EPAM_PROVIDER_SET was
# "REQUIRED" long after that requirement was removed from config.js entirely.
#
# Read from the SAME declared sources the rest of the pipeline already reads. A credential added to
# provider-sets.json or env-vars.json needs no edit here — the next install regenerates it.

# generate_env_example <provider_sets_json> <env_vars_json> <out_file>
#
# env_vars_json may not exist: it is an ADDITION (vars no provider set owns), not a dependency.
generate_env_example() {
    local _provider_sets="$1" _env_vars="$2" _out="$3"
    "${NODE_BIN:-node}" -e '
      const fs = require("fs");
      const [providerSetsFile, envVarsFile, outFile] = process.argv.slice(1, 4);

      const ps = JSON.parse(fs.readFileSync(providerSetsFile, "utf8"));
      const lines = [];
      lines.push("# GENERATED by install.sh from orchestrations/config/provider-sets.json and");
      lines.push("# orchestrations/config/env-vars.json — do not hand-edit this file, edit those.");
      lines.push("# Copy to .env and fill in; re-running the installer regenerates THIS template,");
      lines.push("# never your real .env.");
      lines.push("");

      // ONE ENTRY PER from VAR, even when more than one set declares the same credential — the
      // same source key is the same secret regardless of how many sets want to read it.
      const byVar = new Map();
      for (const [setName, set] of Object.entries(ps.sets || {})) {
        for (const c of (set && set.credentials) || []) {
          if (!c || !c.from) continue;
          const e = byVar.get(c.from) || { sets: [], required: false };
          e.sets.push(setName + (c.required ? "" : " (optional)"));
          e.required = e.required || !!c.required;
          byVar.set(c.from, e);
        }
      }
      if (byVar.size) {
        lines.push("# ── Provider credentials — each is used by the set(s) named ──");
        for (const [name, e] of byVar) {
          lines.push(`# used by: ${e.sets.join(", ")}`);
          lines.push(`${name}=`);
          lines.push("");
        }
      }

      if (fs.existsSync(envVarsFile)) {
        const ev = JSON.parse(fs.readFileSync(envVarsFile, "utf8"));
        const vars = ev.vars || [];
        if (vars.length) {
          lines.push("# ── Feature-scoped — needed only if you use that feature ──");
          for (const v of vars) {
            lines.push(`# ${v.feature}`);
            lines.push(`${v.name}=`);
            lines.push("");
          }
        }
      }

      fs.writeFileSync(outFile, lines.join("\n"));
    ' "$_provider_sets" "$_env_vars" "$_out"
}
