# preserve-operator-config.sh — AN UPDATE MUST NEVER OVERWRITE AN OPERATOR'S EXISTING CONFIG.
#
# `git archive <ref> | tar -x -C dest` overwrites every tracked file the ref contains,
# unconditionally — including project config.env (JIRA_CODELINE_ROOT, JIRA_JQL, ...), which each
# project's own manifest.json already declares role:"config", "Operator-maintained... Never
# regenerated by a run." Found 2026-09-03: repackaging a newer ref into an EXISTING install
# silently reset an operator's JIRA_CODELINE_ROOT edit (pointed at a test copy of the codelines)
# back to whatever HEAD's committed value was, with no warning at all.
#
# UNLIKE run-state-paths.json's excludes, this is NOT "never touch this path" — a blanket exclude
# would also block a brand-new project's config.env from ever being extracted the first time a
# later ref adds one. This is "preserve it IF it already exists, otherwise let the fresh one
# through" — snapshot before extraction, restore after, so a first install (or a genuinely new
# project) is unaffected either way.
#
# The boundary is declared in operator-config-paths.json, not hardcoded here — a new
# operator-config location needs an entry there, not a script edit.

# snapshot_operator_config <root> <json> <tmpdir>
#
# Copies every file at $root matching a declared glob that ALREADY EXISTS into $tmpdir, preserving
# its relative path. A pattern matching nothing (fresh install, or a project not yet present)
# copies nothing — there is nothing to preserve.
snapshot_operator_config() {
    local _root="$1" _json="$2" _tmp="$3"
    [ -f "$_json" ] || return 0
    local _pattern _rel _relpath
    while IFS= read -r _pattern; do
        [ -n "$_pattern" ] || continue
        for _rel in "$_root"/$_pattern; do
            # Unquoted $_pattern is deliberate — it must glob-expand. Without nullglob, no match
            # leaves the literal string; -f screens that out the same as a real non-match.
            [ -f "$_rel" ] || continue
            _relpath="${_rel#"$_root"/}"
            mkdir -p "$(dirname "$_tmp/$_relpath")"
            cp "$_rel" "$_tmp/$_relpath"
        done
    done < <("${NODE_BIN:-node}" -e '
      const fs = require("fs");
      const j = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
      for (const p of j.paths || []) process.stdout.write(p + "\n");
    ' "$_json")
}

# restore_operator_config <root> <tmpdir>
#
# Copies every snapshotted file back over whatever the extraction just wrote at the same relative
# path — the operator's existing config always wins over the packaged ref's committed copy.
restore_operator_config() {
    local _root="$1" _tmp="$2" _f _relpath
    [ -d "$_tmp" ] || return 0
    while IFS= read -r _f; do
        _relpath="${_f#"$_tmp"/}"
        mkdir -p "$(dirname "$_root/$_relpath")"
        cp "$_f" "$_root/$_relpath"
    done < <(find "$_tmp" -type f)
}
