# preserve-operator-config.sh — AN UPDATE MUST NEVER OVERWRITE AN OPERATOR'S EXISTING CONFIG.
#
# `git archive <ref> | tar -x -C dest` overwrites every tracked file the ref contains,
# unconditionally — including project config.env (JIRA_CODELINE_ROOT, JIRA_JQL, ...), which each
# project's own manifest.json already declares role:"config", "Operator-maintained... Never
# regenerated by a run." Found 2026-09-03: repackaging a newer ref into an EXISTING install
# silently reset an operator's JIRA_CODELINE_ROOT edit (pointed at a test copy of the codelines)
# back to whatever HEAD's committed value was, with no warning at all.
#
# UNLIKE run-state-paths.json's excludes, this is NOT "never touch this path" — a blanket exclude
# would also block a brand-new project's config.env from ever being extracted the first time a
# later ref adds one. This is "preserve it IF it already exists, otherwise let the fresh one
# through" — snapshot before extraction, restore after, so a first install (or a genuinely new
# project) is unaffected either way.
#
# The boundary is declared in operator-config-paths.json, not hardcoded here — a new
# operator-config location needs an entry there, not a script edit.

# snapshot_operator_config <root> <json> <tmpdir>
#
# Copies every file at $root matching a declared glob that ALREADY EXISTS into $tmpdir, preserving
# its relative path. A pattern matching nothing (fresh install, or a project not yet present)
# copies nothing — there is nothing to preserve.
snapshot_operator_config() {
    local _root="$1" _json="$2" _tmp="$3"
    [ -f "$_json" ] || return 0
    local _pattern _rel _relpath
    while IFS= read -r _pattern; do
        [ -n "$_pattern" ] || continue
        for _rel in "$_root"/$_pattern; do
            # Unquoted $_pattern is deliberate — it must glob-expand. Without nullglob, no match
            # leaves the literal string; -f screens that out the same as a real non-match.
            [ -f "$_rel" ] || continue
            _relpath="${_rel#"$_root"/}"
            mkdir -p "$(dirname "$_tmp/$_relpath")"
            cp "$_rel" "$_tmp/$_relpath"
        done
    done < <("${NODE_BIN:-node}" -e '
      const fs = require("fs");
      const j = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
      for (const p of j.paths || []) process.stdout.write(p + "\n");
    ' "$_json")
}

# restore_operator_config <root> <tmpdir>
#
# Copies every snapshotted file back over whatever the extraction just wrote at the same relative
# path — the operator's existing config always wins over the packaged ref's committed copy.
# A PRESERVED JSON CATALOGUE IS MERGED, NOT REPLACED. The engine-wide catalogues (agent
# messages, providers, pricing...) gain keys with every ref; preserving the operator's copy
# byte-for-byte meant "a future update also stops delivering THOSE additions" and a hand merge
# — the one thing the install rule forbids (2026-09-20: EscalateDefect's new message codes
# never reached the regintel install). Every key the operator's copy holds keeps the
# operator's value; every key the new ref adds arrives. Anything that is not a JSON object on
# both sides is restored byte-for-byte, as before.
restore_operator_config() {
    local _root="$1" _tmp="$2" _f _relpath
    [ -d "$_tmp" ] || return 0
    while IFS= read -r _f; do
        _relpath="${_f#"$_tmp"/}"
        mkdir -p "$(dirname "$_root/$_relpath")"
        case "$_relpath" in
            *.json)
                if [ -f "$_root/$_relpath" ] && "${NODE_BIN:-node}" -e '
                    const fs = require("fs");
                    const [ops, ref, out] = process.argv.slice(1);
                    let o, r;
                    try { o = JSON.parse(fs.readFileSync(ops, "utf8")); r = JSON.parse(fs.readFileSync(ref, "utf8")); } catch { process.exit(3); }
                    const isObj = (x) => x && typeof x === "object" && !Array.isArray(x);
                    if (!isObj(o) || !isObj(r)) process.exit(3);
                    fs.writeFileSync(out, JSON.stringify({ ...r, ...o }, null, 2) + "\n");
                  ' "$_f" "$_root/$_relpath" "$_root/$_relpath.merged" 2>/dev/null; then
                    mv "$_root/$_relpath.merged" "$_root/$_relpath"
                    continue
                fi
                rm -f "$_root/$_relpath.merged"
                cp "$_f" "$_root/$_relpath"
                ;;
            *) cp "$_f" "$_root/$_relpath" ;;
        esac
    done < <(find "$_tmp" -type f)
}
