/**
 * THE PROMPT LAYER PROVISIONS FOR £0, SO NO SEAM NEEDS A PAID RUN TO BE TESTED.
 *
 * I told the operator twice that 32 of the 40 seams could not be exercised offline, because their
 * project prompts are generated by a model and metrolinx has none. That was wrong, and it was the
 * reason several seams were "unreachable" earlier today.
 *
 * buildProjectPrompts takes runText as a parameter. Stub it and the whole prompt layer appears —
 * all 41 copies — at no cost. This asserts that, so the claim cannot quietly come back.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { provisionProject, REPO } from '../helpers/provisioned-project';

describe('every seam can be driven without spending', () => {
  it('the whole prompt layer provisions with no model call', async () => {
    const p = await provisionProject();
    expect(p.count, 'provisioning produced almost nothing — the stub is not satisfying the builder')
      .toBeGreaterThan(30);
  }, 180_000);

  it('and every seam that declares a template gets its project copy', async () => {
    // The specific claim that was wrong: seams "refuse to render because this project has no
    // prompt". After provisioning, they have one.
    const p = await provisionProject();
    // eslint-disable-next-line @typescript-eslint/no-var-requires, global-require
    const reg = require(join(REPO, 'orchestrations/agents/invocation-profiles.json'));
    const seams = reg.seams || reg.profiles || reg;
    const templates = new Set<string>(
      Object.values<any>(seams).map((s) => s && s.template).filter(Boolean),
    );
    expect(templates.size, 'no seam declares a template — the shape has changed').toBeGreaterThan(20);

    const written = new Set(readdirSync(join(p.dir, 'prompts')).map((f) => f.replace(/\.json$/, '')));
    const missing = [...templates].filter((t) => !written.has(t));
    expect(missing, `these seams still have no project prompt: ${missing.join(', ')}`).toEqual([]);
  }, 180_000);

  it('the copies are real files a renderer will accept', async () => {
    // Structurally real, not specialised. That distinction matters: these say nothing about the
    // project, and are not a substitute for a provisioning run — they are enough to RUN a seam.
    const p = await provisionProject();
    // eslint-disable-next-line @typescript-eslint/no-var-requires, global-require
    const lib = require(join(REPO, 'orchestrations/scripts/lib/prompt-library.js'));
    const one = readdirSync(join(p.dir, 'prompts'))[0].replace(/\.json$/, '');
    expect(existsSync(join(p.dir, 'prompts', `${one}.json`))).toBe(true);
    const doc = lib.loadProjectPrompt(one, p.dir);
    expect(String(doc.body || '').length, `${one} loaded but is empty`).toBeGreaterThan(20);
  }, 180_000);
});
